/**
 * This code was generated by Diez version 10.6.0.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import { Color, GradientStop, LinearGradient, Point2D } from '@diez/prefabs'

const atdColorsColors = {
  profileAvatarYellow: Color.rgba(255, 196, 66, 1),
  profileAvatarAmberYellow: Color.rgba(255, 176, 0, 1),
  profileAvatarLime: Color.rgba(118, 197, 43, 1),
  profileAvatarGreen: Color.rgba(0, 149, 5, 1),
  profileAvatarBlue: Color.rgba(24, 121, 205, 1),
  profileAvatarIndigio: Color.rgba(2, 57, 164, 1),
  profileAvatarViolet: Color.rgba(123, 24, 205, 1),
  profileAvatarDeepPurple: Color.rgba(91, 2, 164, 1),
  profileAvatarPurple: Color.rgba(149, 0, 119, 1),
  profileAvatarRose: Color.rgba(205, 24, 70, 1),
  overlayBlack70: Color.rgba(49, 49, 51, 0.699999988079071),
  white: Color.rgba(255, 255, 255, 1),
  gray200: Color.rgba(244, 244, 244, 1),
  overlayGray20050: Color.rgba(244, 244, 244, 0.5),
  black: Color.rgba(49, 49, 51, 1),
  gray800: Color.rgba(86, 85, 89, 1),
  gray400: Color.rgba(219, 217, 214, 1),
  gray500: Color.rgba(153, 153, 153, 1),
  ctaPrimary: Color.rgba(225, 48, 0, 1),
  ctaSecondary: Color.rgba(103, 102, 106, 1),
  gray600: Color.rgba(103, 102, 106, 1),
  brandYellow: Color.rgba(255, 183, 0, 1),
  brandRed: Color.rgba(193, 0, 19, 1),
  brandOrange: Color.rgba(255, 77, 0, 1),
}

const atdColorsGradients = {
  gradientBrand: new LinearGradient({
    stops: [
      GradientStop.make(0, Color.rgba(255, 183, 0, 1)),
      GradientStop.make(0.536458313465118, Color.rgba(255, 77, 0, 1)),
      GradientStop.make(1, Color.rgba(193, 0, 19, 1)),
    ],
    start: Point2D.make(-4.232861e-9, 0.487499984181486),
    end: Point2D.make(0.987499985466712, 0.487499992721715),
  }),
}

export const atdColorsTokens = {
  colors: atdColorsColors,
  gradients: atdColorsGradients,
}
